# Generated by Django 2.1 on 2019-03-11 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_property'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appliance', models.TextField()),
                ('description', models.TextField()),
                ('workType', models.TextField()),
                ('totalCost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('serviceDate', models.DateTimeField(auto_now_add=True)),
                ('customerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name': 'Property', 'verbose_name_plural': 'Properties'},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.AddField(
            model_name='profile',
            name='firstName',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='lastName',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='propertyID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Property'),
        ),
    ]
