# Generated by Django 2.1 on 2019-04-23 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20190422_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='customerID',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='propertyID',
        ),
        migrations.DeleteModel(
            name='Property',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
