# Generated by Django 2.1 on 2019-04-26 21:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_auto_20190426_0643'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created'),
        ),
    ]
