# Generated by Django 2.1 on 2019-04-27 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='estimatedCost',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
