# Generated by Django 2.1 on 2019-04-27 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20190426_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='requestedServiceDate',
            field=models.DateTimeField(null=True),
        ),
    ]
