# Generated by Django 2.1 on 2019-04-27 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticket_requestedservicedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='customerDescription',
            field=models.TextField(null=True),
        ),
    ]
